import i18n from "i18next";
import { initReactI18next } from "react-i18next";
const resources = {
  tr: {
    translation: {
      welcome: "Hosgeldin!",
      home: 'Hoş Geldiniz Anasayfa! Bizimle birlikte olmanın ayrıcalığını yaşayın. Şirketimiz, müşteri memnuniyetini en üst düzeyde tutmayı hedefler. Yenilikçi çözümlerimiz ve profesyonel ekibimizle hizmetinizdeyiz. Teknolojiye olan tutkumuz ve sektördeki deneyimimizle sizlere en iyi hizmeti sunmak için buradayız. Müşteri odaklı yaklaşımımızla, ihtiyaçlarınızı karşılamak ve beklentilerinizi aşmak için çalışıyoruz. Hakkımızda Şirketimiz, yılların verdiği tecrübe ve yenilikçi yaklaşımıyla sektörde öncü bir konumda bulunmaktadır. Kaliteli hizmet anlayışımız ve profesyonel ekibimizle, müşterilerimizin memnuniyetini en üst düzeyde tutmayı hedefliyoruz. Misyonumuz, müşterilerimizin ihtiyaçlarını anlamak ve onlara en uygun çözümleri sunmaktır. Vizyonumuz ise, sektördeki lider konumumuzu sürdürülebilir kılmak ve sürekli olarak yenilikçi çözümler sunmaktır. Hizmetlerimiz Danışmanlık: İşletmenizin ihtiyaçlarına uygun stratejiler geliştiriyoruz. Teknoloji Çözümleri: Güncel teknolojilerle iş süreçlerinizi optimize ediyoruz. Eğitim: Profesyonel gelişiminize katkı sağlayacak eğitimler sunuyoruz. Destek: 7/24 teknik destek ile her an yanınızdayız. Müşteri Yorumları Ali K.: "Şirketinizin sunduğu hizmetlerden çok memnun kaldım. Profesyonel yaklaşımınız ve çözüm odaklı tavrınız için teşekkür ederim." Zeynep Y.: "Sizinle çalışmak büyük bir ayrıcalık. İş süreçlerimizi daha verimli hale getirdiniz." Mehmet A.: "Her soruma hızlı ve etkili çözümler sundunuz. Müşteri memnuniyetine verdiğiniz önem takdire şayan." İletişim Herhangi bir sorunuz veya hizmet talepleriniz için bize ulaşmaktan çekinmeyin. Sizlere yardımcı olmaktan mutluluk duyarız. Bizimle iletişime geçmek için aşağıdaki bilgilerden yararlanabilirsiniz: Telefon: +90 123 456 78 90 E-posta: info@ornekfirma.com Adres: 1234 Cadde, Şehir, Ülke ',
      about:
        'Hoş Geldiniz Hakkımızda! Bizimle birlikte olmanın ayrıcalığını yaşayın. Şirketimiz, müşteri memnuniyetini en üst düzeyde tutmayı hedefler. Yenilikçi çözümlerimiz ve profesyonel ekibimizle hizmetinizdeyiz. Teknolojiye olan tutkumuz ve sektördeki deneyimimizle sizlere en iyi hizmeti sunmak için buradayız. Müşteri odaklı yaklaşımımızla, ihtiyaçlarınızı karşılamak ve beklentilerinizi aşmak için çalışıyoruz. Hakkımızda Şirketimiz, yılların verdiği tecrübe ve yenilikçi yaklaşımıyla sektörde öncü bir konumda bulunmaktadır. Kaliteli hizmet anlayışımız ve profesyonel ekibimizle, müşterilerimizin memnuniyetini en üst düzeyde tutmayı hedefliyoruz. Misyonumuz, müşterilerimizin ihtiyaçlarını anlamak ve onlara en uygun çözümleri sunmaktır. Vizyonumuz ise, sektördeki lider konumumuzu sürdürülebilir kılmak ve sürekli olarak yenilikçi çözümler sunmaktır. Hizmetlerimiz Danışmanlık: İşletmenizin ihtiyaçlarına uygun stratejiler geliştiriyoruz. Teknoloji Çözümleri: Güncel teknolojilerle iş süreçlerinizi optimize ediyoruz. Eğitim: Profesyonel gelişiminize katkı sağlayacak eğitimler sunuyoruz. Destek: 7/24 teknik destek ile her an yanınızdayız. Müşteri Yorumları Ali K.: "Şirketinizin sunduğu hizmetlerden çok memnun kaldım. Profesyonel yaklaşımınız ve çözüm odaklı tavrınız için teşekkür ederim." Zeynep Y.: "Sizinle çalışmak büyük bir ayrıcalık. İş süreçlerimizi daha verimli hale getirdiniz." Mehmet A.: "Her soruma hızlı ve etkili çözümler sundunuz. Müşteri memnuniyetine verdiğiniz önem takdire şayan." İletişim Herhangi bir sorunuz veya hizmet talepleriniz için bize ulaşmaktan çekinmeyin. Sizlere yardımcı olmaktan mutluluk duyarız. Bizimle iletişime geçmek için aşağıdaki bilgilerden yararlanabilirsiniz: Telefon: +90 123 456 78 90 E-posta: info@ornekfirma.com Adres: 1234 Cadde, Şehir, Ülke',
      contact:
        'Hoş Geldiniz İletişim! Bizimle birlikte olmanın ayrıcalığını yaşayın. Şirketimiz, müşteri memnuniyetini en üst düzeyde tutmayı hedefler. Yenilikçi çözümlerimiz ve profesyonel ekibimizle hizmetinizdeyiz. Teknolojiye olan tutkumuz ve sektördeki deneyimimizle sizlere en iyi hizmeti sunmak için buradayız. Müşteri odaklı yaklaşımımızla, ihtiyaçlarınızı karşılamak ve beklentilerinizi aşmak için çalışıyoruz. Hakkımızda Şirketimiz, yılların verdiği tecrübe ve yenilikçi yaklaşımıyla sektörde öncü bir konumda bulunmaktadır. Kaliteli hizmet anlayışımız ve profesyonel ekibimizle, müşterilerimizin memnuniyetini en üst düzeyde tutmayı hedefliyoruz. Misyonumuz, müşterilerimizin ihtiyaçlarını anlamak ve onlara en uygun çözümleri sunmaktır. Vizyonumuz ise, sektördeki lider konumumuzu sürdürülebilir kılmak ve sürekli olarak yenilikçi çözümler sunmaktır. Hizmetlerimiz Danışmanlık: İşletmenizin ihtiyaçlarına uygun stratejiler geliştiriyoruz. Teknoloji Çözümleri: Güncel teknolojilerle iş süreçlerinizi optimize ediyoruz. Eğitim: Profesyonel gelişiminize katkı sağlayacak eğitimler sunuyoruz. Destek: 7/24 teknik destek ile her an yanınızdayız. Müşteri Yorumları Ali K.: "Şirketinizin sunduğu hizmetlerden çok memnun kaldım. Profesyonel yaklaşımınız ve çözüm odaklı tavrınız için teşekkür ederim." Zeynep Y.: "Sizinle çalışmak büyük bir ayrıcalık. İş süreçlerimizi daha verimli hale getirdiniz." Mehmet A.: "Her soruma hızlı ve etkili çözümler sundunuz. Müşteri memnuniyetine verdiğiniz önem takdire şayan." İletişim Herhangi bir sorunuz veya hizmet talepleriniz için bize ulaşmaktan çekinmeyin. Sizlere yardımcı olmaktan mutluluk duyarız. Bizimle iletişime geçmek için aşağıdaki bilgilerden yararlanabilirsiniz: Telefon: +90 123 456 78 90 E-posta: info@ornekfirma.com Adres: 1234 Cadde, Şehir, Ülke',
      footer1: "About us",
      footer2:
        " Biz, müşteri memnuniyetini ön planda tutan bir şirketiz.  Misyonumuz, en kaliteli hizmeti sunmaktır.",
      footer3: "Bağlantılar",
      footer4: "Anasayfa",
      footer5: "Hakkımızda",
      footer6: "Hizmetler",
      footer7: "İletişim",
      footer9: "Adres: 1234 Sokak, Şehir, Ülke",
      footer10: "Telefon: +90 553 159 9002",
      footer11: "Email: info@ornek.com",
      footer12: "2024 Tüm hakları saklıdır. Furkan İzci.",
      header1: "Ana Sayfa",
      header2: "Hakkımızda",
      header3: "Hizmetler",
      header4: "İletişim",
    },
  },
  en: {
    translation: {
      welcome: "Welcome!",
      home: 'Welcome Home Page! It protects its assets with us. Our company aims to keep its customer base at the highest level. We are at your service with our innovative solutions and professional team. We are here to offer you the best service with our passion for technology and experience in the sector. With our customer-focused approach, we work to meet your needs and exceed your expectations. About Us Our company has a long life with its years of historical experience and close approach. We aim to keep the scope at the highest level with our quality service approach and professional team. Our mission is to create components and provide them with suitable solutions. Our vision is to maintain our leading position in the industry by providing sustainable and constantly analytical solutions. Our Services Consultancy: We develop appropriate strategies for your business. Technology Solutions: We optimize your business with current technologies. Training: We offer training that contributes to your professional development. Support: We are here for you with 24/7 technical support. Customer Comments Ali K.: "I am very pleased with the services provided by your company. Thank you for your professional approach and solution-oriented attitude." Zeynep Y.: "It is a great privilege to work with you. You have made our work more efficient." Mehmet A.: "You offered fast and effective solutions to all my questions. The importance you attach to customer satisfaction is admirable." Contact Feel free to contact us with any questions or to provide your services. We would be happy to assist you in the future. You can use the following information to get the application form with us: Phone: +90 123 456 78 90 E-mail: info@ornekfirma.com Address: 1234 Street, City, Country',
      about:
        'Welcome About Us! Enjoy the privilege of being with us. Our company aims to keep customer satisfaction at the highest level. We are at your service with our innovative solutions and professional team. We are here to offer you the best service with our passion for technology and experience in the sector. With our customer-focused approach, we work to meet your needs and exceed your expectations. About Us Our company is in a leading position in the sector with its years of experience and innovative approach. We aim to keep our customers satisfaction at the highest level with our quality service approach and professional team. Our mission is to understand our customers needs and offer them the most suitable solutions. Our vision is to sustain our leading position in the industry and to constantly offer innovative solutions. Our Services Consultancy: We develop strategies that suit the needs of your business. Technology Solutions: We optimize your business processes with current technologies. Training: We offer training that will contribute to your professional development. Support: We are always at your service with 24/7 technical support. Customer Comments Ali K.: "I am very pleased with the services provided by your company. Thank you for your professional approach and solution-oriented attitude." Zeynep Y.: "It is a great privilege to work with you. You have made our business processes more efficient." Mehmet A.: "You offered fast and effective solutions to all my questions. The importance you attach to customer satisfaction is admirable." Contact Do not hesitate to contact us for any questions or service requests. We would be happy to assist you. You can use the following information to contact us: Phone: +90 123 456 78 90 E-mail: info@ornekfirma.com Address: 1234 Street, City, Country',
      contact:
        'Welcome Contact! Enjoy the privilege of being with us. Our company aims to keep customer satisfaction at the highest level. We are at your service with our innovative solutions and professional team. We offer you the best with our passion for technology and experience in the sector. We are here to provide service. With our customer-oriented approach, We strive to meet your needs and exceed your expectations. About Us Our company, with its years of experience and innovative approach It is in a leading position in the industry. Our understanding of quality service and With our professional team, we ensure the satisfaction of our customers at the highest level. We aim to keep it. Our mission is to understand our customers needs and to offer them the most suitable solutions. Our vision is to be the leader in the industry. To make our position sustainable and to constantly provide innovative solutions to present. Our Services Consultancy: Suitable for the needs of your business We are developing strategies. Technology Solutions: Working with current technologies We optimize your processes. Education: Contribution to your professional development We offer training that will provide Support: Any time with 24/7 technical support We are with you. Customer Comments Ali K.: "From the services offered by your company I was very pleased. For your professional approach and solution-oriented attitude Thank you." Zeynep Y.: "It is a great privilege to work with you. Work You have made our processes more efficient." Mehmet A.: "I answered all my questions quickly. and you offered effective solutions. The importance you attach to customer satisfaction is appreciated. Contact us for any questions or service requests. Dont hesitate to reach out. We would be happy to assist you. With us You can use the following information to contact us: Phone: +90 123 456 78 90 E-mail: info@ornekfirma.com Address: 1234 Caddesi, City, Country',
      footer1: "About us",
      footer2:
        " We are a company that prioritizes customer satisfaction.  Our mission is to provide the highest quality service.",
      footer3: "Links",
      footer4: "Home",
      footer5: "About US",
      footer6: "Services",
      footer7: "Contact",
      footer9: "Address: 1234 Street, City, Country",
      footer10: "Phone: +90 553 159 9002",
      footer11: "Email: info@ornek.com",
      footer12: "2024 All rights reserved. Furkan İzci.",
      header1: "Home",
      header2: "About Us",
      header3: "Services",
      header4: "Contact",
    },
  },
};
i18n.use(initReactI18next).init({
  lng: localStorage.getItem('language') || 'tr',
  resources,
});

export default i18n;
